### PR TITLE
[doc] adding the doc to describe the new api

### PR DESCRIPTION
**Pull request by JiahaoYao**
this pr is to add the explanation of using the new api (https://github.com/alpa-projects/alpa/pull/657). 

Not sure this is the best place to add the description, but it will show in the [online tutorials](https://alpa.ai/tutorials/pipeshard_parallelism.html#connect-to-a-ray-cluster). 

@zhisbug

### CODE REVIEW

**Comment by zhisbug** [comment]
@JiahaoYao Yeah that's fine.

In addition, I am thinking that we can expand the doc/tutorials to have a new misc tutorial called "HOWTO".

Many people have been asking the question in Slack about how to let Alpa use partial GPUs of a node. You can add a section to celebrate two ways to control the GPUs Alpa can use: (1) use CUDA_VISIBLE_DEVICES when starting ray (2) use your API

**Comment by JiahaoYao** [comment]
Cool, sgtm, and i would appreciate the howto pages like [this](https://jax.readthedocs.io/en/latest/notebooks/thinking_in_jax.html) if i am an user.

**Comment by merrymercy** [comment]
We can create a new page called "FAQ" under "tutorial"

**Comment by JiahaoYao** [comment]
sounds good to me!

**Review by merrymercy — APPROVED** [review]

**Pull request merged**
