### PR TITLE
Add rng_normal support

### PR DESCRIPTION
**Pull request by yf225**
Previous discussion: https://github.com/alpa-projects/alpa/issues/372

### CODE REVIEW

**Comment by zhisbug** [comment]
LGTM. @merrymercy may have additional comments

**Review by merrymercy — COMMENTED** [review]
LGTM. Please fix the linting

**Comment by yf225** [comment]
Thanks! Fixed lint

**Comment by zhisbug** [comment]
the secret token is not visible in the forks. I'll fix this shortly and rerun your pipeline.

**Pull request merged**
