### PR TITLE
updated functorch imports for PyTorch2 frontend

### PR DESCRIPTION
**Pull request by Vatshank**
Hi, 

I am looking into using the PT frontend for Alpa. The current code works for PT1.12 but breaks for PT1.13 and PT2. To get the tests in `torch_frontend/*` to pass for PT2, I had to update some of the functorch imports under `alpa/torch/__init__.py`. The tests pass but let me know if there is some additional testing that needs to be done to update the PT frontend.

### CODE REVIEW

**Comment by ZYHowell** [comment]
Can you please fix the CI and update the branch?

**Comment by Vatshank** [comment]
@ZYHowell, I ran the linting script and rebased on the main branch. I think it still needs your approval to kick off the CI tests.

**Comment by Vatshank** [comment]
@ZYHowell, the `runtime.test_device_mesh.DeviceMesh_ResourceAwareness` is failing but I am not sure why. When I ran it locally (G5 ec2 instance with 4 GPUs), it failed the first time but when I ran it again, it seems to pass. Not sure what is going on here, seems unrelated to the PT frontend changes I made?

**Comment by ZYHowell** [comment]
That seems like some stability issue of our CI. I reran the test and now it shows some torch-related error. Seems like this is because the new version api is not compatible with old versions. Can you please update your code to make it compatible? The anticipated code may be like:
```python
if torch.__version__ < xxx:
  from functorch._C import xxx
else:
  from torch._C._functorch import xxx
```

**Comment by Vatshank** [comment]
Thanks @ZYHowell! I have added the version specific imports.

**Review by ZYHowell — APPROVED** [review]
LGTM. Thanks for you contribution!

**Pull request merged**
