### PR TITLE
[Feature] Support multiple executables in OPT serving

### PR DESCRIPTION
**Pull request by comaniac**
The initial support of multiple executables to cover various input prompt lengths.

Usage (note that this is only applicable to autoregressive mode):
```
python benchmark_text_gen.py --model alpa/opt-2.7b --path ... --multi-executable
```

Since this is only for benchmarking, currently we check all prompts we are going to run and make a list of decoder lengths accordingly.

Next steps:
- Enable parameter sharing between executables (#550). Now we encounter the following error, which should be caused by different input shardings.
```
  File "/home/ubuntu/alpa/alpa/pipeline_parallel/pipeshard_executable.py", line 221, in __call__
    out = self.launch_on_driver(*args_flat)
  File "/home/ubuntu/alpa/alpa/pipeline_parallel/pipeshard_executable.py", line 150, in launch_on_driver
    self.num_batch, mesh_args)
  File "/home/ubuntu/alpa/alpa/device_mesh.py", line 1117, in shard_args_to_bufs
    assert replica.indices == indices
AssertionError
```
- Fix the bug of crashing with non-power-of-2 prompt (#561). The current error is:
```
  File "/home/ubuntu/alpa/alpa/pipeline_parallel/cross_mesh_resharding.py", line 1067, in dst_tile_to_src_tiles_map
    self._dst_tile_to_src_tiles_map = self.generate_src_dst_map()
  File "/home/ubuntu/alpa/alpa/pipeline_parallel/cross_mesh_resharding.py", line 1085, in generate_src_dst_map
    self._look_up_dst_tile_from_src(tile))
  File "/home/ubuntu/alpa/alpa/pipeline_parallel/cross_mesh_resharding.py", line 1113, in _look_up_dst_tile_from_src
    assert not ragged
AssertionError
```
- Support input padding. Currently we compile one executable for a prompt. However, ideally we should limit the executable number and pad the input prompt to fit the pre-compiled executable with the nearest decoding length.
- Improve performance. Now multiple executables will introduce some overheads at the certain iteration (e.g., 50) during text generation, so that its end-to-end latency is longer than the single executable. I'm still investigating the root cause.

cc @zhisbug @zhuohan123 @merrymercy

### CODE REVIEW

**Comment by merrymercy** [comment]
The second bug is fixed. Could you tell me how to re-produce the first bug?

**Comment by comaniac** [comment]
It's easier to reproduce the first one based on this PR. You could change the function `load_multi_executable_params_dis_array` to make it call `load_params_dis_array` just once and return the same params for all executables. I've verified that currently every executable has different input sharding, so it's likely the root cause.

**Comment by merrymercy** [comment]
I tried your branch and reproduced the problem. After #574, I found that 99% of sharding specs are identical. Only a few arrays at the boundary of pipeline stages have different sharding specs. I will think about how to fix this, but I don't have time to do it in the next few days.

Besides the padding and performance problem, I also found the generation results not correct.

## Single Executable
```
ubuntu@ip-172-31-36-188:~/efs/alpa/examples/opt_serving/benchmark$ python3 benchmark_text_gen.py --model alpa/opt-2.7b  --debug
Load model alpa/opt-2.7b ... (This can take several minutes for very large models)
2022-07-02 05:38:28,563 INFO worker.py:840 -- Connecting to existing Ray cluster at address: 172.31.36.188:6379
Compiling 1 executable(s) for decoding length [1]
input length: 8, output_length: 256, num_gpus: 8, speed: 48.70 tokens/s, tflops: 0.0363 tflops/s
['Computer science is the study of computation and information. It is the study of how information is processed and stored. It is the study of how computers work. It is the study of how computers are used. It is the study of how computers are programmed. It is the study of how computers are used. It is the study of how computers are programmed. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of']
Model: alpa/opt-2.7b  Device: cuda  Dummy: False  Load (s): 35.54  Autoregressive: True  Batchsize: 1  #Microbatches: 1  #Stages: 2  Decoder step length: 1  TFlops: 0.0036  Compute TFlops: 0.0075  Speed (token/s): 4.87  latency (32 token): 6.57
```

## Multi Executable
```
ubuntu@ip-172-31-36-188:~/efs/alpa/examples/opt_serving/benchmark$ python3 benchmark_text_gen.py --model alpa/opt-2.7b  --multi-executable --debug
Load model alpa/opt-2.7b ... (This can take several minutes for very large models)
2022-07-02 05:36:38,662 INFO worker.py:840 -- Connecting to existing Ray cluster at address: 172.31.36.188:6379
Compiling 2 executable(s) for decoding length [8, 1]
input length: 8, output_length: 256, num_gpus: 8, speed: 51.03 tokens/s, tflops: 0.0380 tflops/s
['Computer science is the study of computation and the same\n\n\n\n\nThe a\n\nThe first time of the first time I saw the first time I saw this, I saw this, I thought it, I thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke.\n\nI thought it was a joke']
Model: alpa/opt-2.7b  Device: cuda  Dummy: False  Load (s): 56.15  Autoregressive: True  Batchsize: 1  #Microbatches: 1  #Stages: 2  Decoder step length: [8, 1]  TFlops: 0.0038  Compute TFlops: 0.0078  Speed (token/s): 5.10  latency (32 token): 6.27
```

**Comment by comaniac** [comment]
Hmm looks like the cache shared by executables wasn't correctly used. I'll try to fix it next week.

**Comment by comaniac** [comment]
The correctness problem has been resolved. There are two points in OPT model that do not consider prompt>1:
1. The attention bias (Fixed in #608 ).
2. Input position IDs (Fixed in this PR).

The results with multiple executables:
```
Computer science is the study of computation and information. It is the study of how information is processed and stored. It is the study of how computers work. It is the study of how computers are used. It is the study of how computers are programmed. It is the study of how computers are used. It is the study of how computers are programmed. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of how computers are used. It is the study of
```

**Comment by comaniac** [comment]
Update: The input_sharding_spec is added. Now we apply input_sharding_spec from executable-1 to all executables.
This requires https://github.com/alpa-projects/tensorflow-alpa/pull/126.

**Comment by merrymercy** [comment]
I reviewed all relevant PRs. Let me know when all results are ready and we get speedup with multiple executables (on a long prompt), then I will review again.

**Comment by comaniac** [comment]
This PR is ready for review and merge. Meanwhile, I'm not sure about how should we do with #623

**Comment by merrymercy** [comment]
One user requires this feature because his prompt is very long. Currently, alpa is too slow for long prompts. I will take over this and let you prioritize the long-term 1D OPT solution.

**Comment by merrymercy** [comment]
https://github.com/alpa-projects/alpa/pull/661

**Pull request closed without merging**
