### PR TITLE
[Alpa Runtime] update the alpa api for resources awareness

### PR DESCRIPTION
**Pull request by JiahaoYao**
> Hello! Sorry maybe a silly question, but is there a configuration for alpa to use only a subset of the # of gpus? (Ie. only run 2 cores when 8 cores are available) Do I have to create a device mesh for it? 

People prefer to set the configuration for the alpa instead of using the whole cluster. This PR is try to enrich the resources allocation with a easy-to-use api.

image

@zhisbug @merrymercy 

- [x] adding the `cpu=1e-4` for the `daemonworker`.

### CODE REVIEW

**Comment by JiahaoYao** [comment]
btw, @merrymercy do u have any suggestions about the uni-test for this pr?

**Comment by JiahaoYao** [comment]
ready to review with the test

**Review by merrymercy — APPROVED** [review]

**Comment by zhisbug** [comment]
@JiahaoYao any chance you can add a documentation for this API?

**Comment by JiahaoYao** [comment]
SGTM, @zhisbug where is the best place for this documentation?

**Pull request merged**
