### PR TITLE
bypass nodes which don't have gpu resources.

### PR DESCRIPTION
**Pull request by dumpmemory**
try to pass the nodes which don't have gpu resources.

in my setting, the ray head node don't have any cpu or gpu resources so we might need to skip these nodes.

### CODE REVIEW

**Comment by dumpmemory** [comment]
i might need to consider this  #https://github.com/alpa-projects/alpa/issues/776#issue-1447588779

**Comment by merrymercy** [comment]
This seems to be a reasonable fix.

1. Could you fix the lint error?
2. Did this solve your problem?  I guess there might be other places we also need to bypass nodes without GPU resources.

**Comment by dumpmemory** [comment]
1. I will try to fix the lint error
2. no i still facing the problem like #https://github.com/alpa-projects/alpa/issues/776#issue-1447588779. the grpc is failed. in my ray cluster setting, the training process is deployed on the worker node with gpus, which means there is no workload on head node. So there must be other places need to modified 
3.

**Comment by dumpmemory** [comment]
1.  the grpc issues should be fixed by https://github.com/alpa-projects/alpa/pull/803#issue-1478530799

**Comment by ZYHowell** [comment]
@dumpmemory sorry I missed point 3 in your last reply and thought the problem in this issue is fully addressed , so I merged main into this branch with some change as a pre-merge process. If you have other commits, please forcely push to cover mine

**Comment by dumpmemory** [comment]
> @dumpmemory sorry I missed point 3 in your last reply and thought the problem in this issue is fully addressed , so I merged main into this branch with some change as a pre-merge process. If you have other commits, please forcely push to cover mine

For the third question is that  i can't use PipeshardParallel to find a parallel setting for 1.3b gpt-neo model on 8 2080 ti gpus. This might be because i am not  familiar with the alpa yet. which might not related to this pr. pls ignore it. Thanks again

**Comment by dumpmemory** [comment]
1. I have test it on my side by running https://github.com/alpa-projects/alpa/blob/main/tests/pipeline_parallel/test_bert.py and https://github.com/alpa-projects/alpa/blob/main/examples/gpt2/run_clm_flax.py （with gpt-neo 125m ） and it all passed. 
2. I haven't run https://github.com/alpa-projects/alpa/blob/main/tests/shard_parallel/test_bert.py. But when i modify the run_clm_flax.py using ShardParallel method, it failed with #810. it seems that the peak_memory is inf.

**Comment by dumpmemory** [comment]
The bypass GPU pr pass https://github.com/alpa-projects/alpa/blob/main/tests/shard_parallel/test_bert.py test.

**Review by zhuohan123 — APPROVED** [review]
LGTM

**Pull request merged**
