### PR TITLE
Add example OPT-IML configs

### PR DESCRIPTION
**Pull request by dlzou**

### CODE REVIEW

**Comment by merrymercy** [comment]
Could it run? Which commands did you test?

**Comment by dlzou** [comment]
@merrymercy Yes, I ran `python3 textgen.py --model alpa/opt-iml-max-1.3b` and `python3 textgen.py --model alpa/opt-iml-max-30b` successfully on a system with eight P100s.

**Comment by merrymercy** [comment]
Cool. Is it ready for merge?

**Comment by dlzou** [comment]
Yes!

**Pull request merged**
