### PR TITLE
[OPT] Unify forward-only and autoregressive benchmark

### PR DESCRIPTION
**Pull request by comaniac**
This PR unifies two benchmark modes for OPT. Specifically:
1. Forward-only mode now takes cache.
2. Forward-only mode will use `test_prompts` if the user-specified decoder length matches any of them.
3. Unify the wrapper interface `__call__` by moving the prompt decomposing logic to autoregressive specific inference function.

I'll further debug the cache issue with this PR.

cc @merrymercy

### CODE REVIEW

**Review by merrymercy — APPROVED** [review]

**Comment by merrymercy** [comment]
@zhisbug If you don't have any comments, I will merge this in 6 hours

**Comment by merrymercy** [comment]
@zhisbug If you don't have any comments, I will merge this in 6 hours
@comaniac Please fix the conflicts.

It seems we should also add some unit test for OPT

**Comment by merrymercy** [comment]
It seems this is not compatible with #623. I don't know how we should merge this

**Comment by comaniac** [comment]
We could merge the batch inference maybe as this PR itself is mainly just for code cleaning.

**Comment by zhisbug** [comment]
@comaniac I have merged the batched inference PR; could you rebase and see if everything works well? Then we can merge this one

**Comment by comaniac** [comment]
We discussed this last week. Please go ahead and merge #623, and I'll implement another PR for multi-executable with 1-D OPT support later, as we are not bucketing based on sequence length anymore. This PR will eventually be closed.

**Comment by merrymercy** [comment]
Close Stale Issues

**Pull request closed without merging**
