### PR TITLE
[FEATURE] beam size and num return sequences for interactive hosting

### PR DESCRIPTION
**Pull request by vinlnx**

### CODE REVIEW

**Comment by vinlnx** [comment]
Removed "n slider" so that it always returns all beams.  Also made the output boxes prettier by converting them to tabs.

**Comment by zhisbug** [comment]
@vinlnx could you rebase master and see if it works still well?

**Comment by vinlnx** [comment]
@zhisbug merged and tested

**Comment by merrymercy** [comment]
@zhisbug please follow up

**Comment by zhisbug** [comment]
@vinlnx I'm fixing some issue in this PR and will merge it once I'm done

**Comment by merrymercy** [comment]
@zhisbug Please rebase and use the new `get_model` API
https://github.com/alpa-projects/alpa/blob/6562734285d372a4c6eb712f42d488cec7c4414f/examples/opt_serving/model/wrapper.py#L221-L260

**Review by zhisbug — APPROVED** [review]

**Comment by zhisbug** [comment]
@vinlnx Thanks!
Now the website can support beam search or return multiple sequence results.

One caveat is that when setting num_return_sequence to a bigger value we might have OOM.

**Pull request merged**
