### PR TITLE
try to fix the issue mentioned in issue #610

### PR DESCRIPTION
**Pull request by JiahaoYao**
i got the lint 

```python
Alpa Pylint:
************* Module alpa.device_mesh
alpa/device_mesh.py:1108:8: W0702: No exception type(s) specified (bare-except)
alpa/device_mesh.py:1957:8: W0702: No exception type(s) specified (bare-except)
************* Module alpa.collective.collective
alpa/collective/collective.py:741:12: W0702: No exception type(s) specified (bare-except)
alpa/collective/collective.py:742:25: W0212: Access to a protected member _private of a client class (protected-access)
alpa/collective/collective.py:797:4: W0702: No exception type(s) specified (bare-except)
alpa/collective/collective.py:798:17: W0212: Access to a protected member _private of a client class (protected-access)
************* Module alpa.collective.collective_group.gloo_collective_group
alpa/collective/collective_group/gloo_collective_group.py:43:8: W0702: No exception type(s) specified (bare-except)

-----------------------------------
Your code has been rated at 9.99/10
```

Any idea to fix this?

### CODE REVIEW

**Comment by JiahaoYao** [comment]
tag: https://github.com/alpa-projects/alpa/issues/610

**Comment by merrymercy** [comment]
Use to fix the lint error
```python
try:
    worker = ray.worker.global_worker
except ModuleNotFoundError:
    worker = ray._private.worker.global_worker
```

**Comment by JiahaoYao** [comment]
done @merrymercy

**Comment by JiahaoYao** [comment]
close #610

**Review by merrymercy — CHANGES_REQUESTED** [review]
This introduces some redundant code. Could you add a new function `get_ray_worker()` in `alpa/util.py`

**Review by merrymercy — APPROVED** [review]

**Pull request merged**
