### PR TITLE
Add xla server port config and pass next batches uuids ==(none,)

### PR DESCRIPTION
**Pull request by dumpmemory**
1. add xla server port config when the docker port are limited to special range  like 8000~8999, should fix  https://github.com/alpa-projects/alpa/issues/826 
2. conner case when next_batches_uuids ==(None,) should fix https://github.com/alpa-projects/alpa/issues/797
3.

### CODE REVIEW

**Comment by dumpmemory** [comment]
The first issue is not totally fixed.

**Comment by dumpmemory** [comment]
Another is when the run_clm_flax_opt.py job finished, the port was not closed as expect

**Comment by merrymercy** [comment]
Thanks for fixing these bugs! It is merged.

**Comment by dumpmemory** [comment]
> Thanks for fixing these bugs! It is merged.

For the first issues, the used port is from ray side. When the job finished, the port was still used by IDLE which was from main function. i am checking it. Thanks .

**Comment by dumpmemory** [comment]
fixed, when  adding ray.remote to the main function in https://github.com/dumpmemory/alpa/blob/49818ad85da01a52f86e3c2b92e9681d991c4639/examples/opt_finetune/test_run_clm_flax_opt.py , must add alpa.shutdown() to close the port.

**Pull request merged**
