### PR TITLE
Correct the implementation of ZHEN

### PR DESCRIPTION
**Pull request by crazyboycjr**
The implementation of current ZHEN has a little mistake. This patch fixes the issue.

### CODE REVIEW

**Comment by zhisbug** [comment]
@crazyboycjr Does this affect CI? If not I can approve and merge

**Comment by crazyboycjr** [comment]
@zhisbug No, it does not affect CI.

**Comment by zhisbug** [comment]
@crazyboycjr cheers! thanks for the first contribution

**Comment by crazyboycjr** [comment]
Thanks @zhisbug! The changes are quite minor, @yf225 can also take a quick look.

**Comment by yf225** [comment]
LGTM, thanks @crazyboycjr!

**Comment by merrymercy** [comment]
@crazyboycjr  I cannot run `test_zhen.py` after this PR

```
======================================================================
ERROR: test_zhen_homogeneous (__main__.TorchZHENTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_zhen.py", line 476, in test_zhen_homogeneous
    loss_func, optim_gen, parallel_method)
  File "/home/ubuntu/efs/alpa/alpa/torch/trainer.py", line 104, in train_torch_module
    state, loss_value = train_step(state, pt_batch)
  File "/home/ubuntu/efs/alpa/alpa/torch/trainer.py", line 61, in train_step
    targets)
  File "/home/ubuntu/efs/alpa/alpa/torch/__init__.py", line 87, in wrapper
    output = func(*args, **kwargs)
  File "/home/ubuntu/efs/alpa/alpa/torch/trainer.py", line 52, in compute_loss
    bufs, out = module_func(params, bufs, inputs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1150, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/efs/alpa/alpa/torch/nn/__init__.py", line 323, in forward
    return buffers, self.stateless_model(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1150, in _call_impl
    return forward_call(*input, **kwargs)
  File "test_zhen.py", line 424, in forward
    input, skip_connection = layer(skip_connection, input)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1150, in _call_impl
    return forward_call(*input, **kwargs)
  File "test_zhen.py", line 362, in forward
    bias=self.layer_norm_b,
  File "/home/ubuntu/.local/lib/python3.7/site-packages/torch/nn/functional.py", line 2501, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Expected weight to be of same shape as normalized_shape, but got weight of shape [64] and normalized_shape = [240]
```

**Pull request merged**
