### PR TITLE
[FEATURE] OPT-175B service authentication and new priority queue

### PR DESCRIPTION
**Pull request by JubilantJerry**
See the issue page https://github.com/alpa-projects/alpa/issues/700. I made some design choices based on my comment there, see if the design choices make sense.

### CODE REVIEW

**Comment by JubilantJerry** [comment]
Example informal test that I've done:

I set the weight for API key `"key1"` to be default and `"key2"` to be 3 times higher.

I've run the following on the command line
```
for i in $(seq 0 20); do ( curl -d '{"model": "default", "prompt": ["This year,", "This month,"], "max_tokens": 16, "api_key": "key1"}' -H 'Content-Type:application/json' localhost:20001/completions && echo "
AAAAAAA$i" ) & done
for i in $(seq 0 20); do ( curl -d '{"model": "default", "prompt": ["This year,", "This month,"], "max_tokens": 17, "api_key": "key2"}' -H 'Content-Type:application/json' localhost:20001/completions && echo "
BBBBBBB$i" ) & done
for i in $(seq 0 20); do ( curl -d '{"model": "default", "prompt": ["This year,", "This month,"], "max_tokens": 18, "api_key": ""}' -H 'Content-Type:application/json' localhost:20001/completions && echo "
CCCCCCC$i" ) & done
for i in $(seq 0 20); do ( curl -d '{"model": "default", "prompt": ["This year,", "This month,"], "api_key": "key1", "top_k": 10}' -H 'Content-Type:application/json' localhost:20001/logprobs && echo "
LLLLLLL$i" ) & done
for i in $(seq 0 20); do ( curl -d '{"model": "default", "prompt": ["This year,", "This month,"], "api_key": "", "top_k": 10}' -H 'Content-Type:application/json' localhost:20001/logprobs && echo "
DDDDDDD$i" ) & done
```

At the same time, I start making requests with several tabs on the web interface.

The result is that:

1. The web interface requests are handled with low latency,
2. The `BBBBBBB` requests are served about 3 times more often than the `AAAAAAA` requests,
3. The `CCCCCCC` and `LLLLLLL` requests are served about 10 times less often than the `AAAAAAA` requests,
4. The `DDDDDDD` requests are served a few times while the other tasks exist, then the remaining requests get handled

**Comment by merrymercy** [comment]
Thanks for your contribution. I replied to your comments. I will review this PR later this week.

**Comment by merrymercy** [comment]
Looks like the code is well-documented and well-tested. The design is what we want in #700 and it carefully considers a lot of potential issues.
Thanks for your contribution! I will do more tests and try to deploy it on our website. I will merge this first as the code holds a very high quality.

**Review by JubilantJerry — COMMENTED** [review]
That's good to hear, I haven't used automated test suites unlike the rest of Alpa but hopefully the informal tests are good enough coverage. I realize that one of the comments is wrong, but that can be fixed elsewhere (I'll include it in #870 in case that feature gets added)

**Pull request merged**
